name: inf281_app
description: "Aplicación para edificio inteligente"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado y almacenamiento
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.8

  # HTTP y APIs
  http: ^1.1.0

  # Gestión de archivos e imágenes - SOLO image_picker
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3

  # Fechas y internacionalización
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
